# Generated by Django 3.2.6 on 2021-08-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.TextField(max_length=25)),
                ('Employee_department', models.CharField(max_length=15)),
            ],
        ),
    ]
